### ISSUE TITLE
Add hooks for subclasses to FeadReader

### ISSUE THREAD

**Issue by steffenmalisi** [rest-feeds/restfeed-client-java#1]
For subclasses it may be useful to control some flows of its parent FeedReader.

In my case I want to build a FeadReader that is capable of running multiple instances in parallel, but only one of them should actually read. To give you an idea, i think it is best to look at the code:

https://github.com/steffenmalisi/restfeed-client-java/blob/feature/failover-feed-reader/src/main/java/org/restfeeds/client/FailOverSingleInstanceFeedReader.java

**Comment by steffenmalisi** [comment]
@jochenchrist Could you please have a look?

**Comment by steffenmalisi** [comment]
@jochenchrist any thoughts on this?

**Comment by jochenchrist** [comment]
I like the hooks.

I am wondering if it could be useful to inject the read items into the `onAfterRead` hook.
Then I'd would move the onAfterRead invocation into the try block.

What do you think?

**Comment by steffenmalisi** [comment]
HI @jochenchrist, 

sounds like a good idea. I updated my PR #2 accordingly. To be more precise I changed the name of the method to ```onAfterReadSuccess```

**Comment by jochenchrist** [comment]
Thanks.
I merged the proposed changes.
